networks:
  webdir:
    driver: bridge

services:

  php:
    image: canals/php:latest
    restart: unless-stopped
    container_name: sae-s4-php-container
    ports:
      - "14200:80"
    depends_on:
      - mysql
    volumes:
      - ./admin/public:/var/www/html
      - ./admin/src:/var/www/src
    networks:
      - webdir
      
  api:
    image: canals/php:latest
    restart: unless-stopped
    container_name: sae-s4-api-container
    ports:
      - "14201:80"
    depends_on:
      - mysql
    volumes:
      - ./api/public:/var/www/html
      - ./api/src:/var/www/src
    networks:
      - webdir

  mysql:
    image: mariadb:latest
    restart: unless-stopped
    container_name: sae-s4-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "14202:3306"
    networks:
      - webdir

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: sae-s4-phpmyadmin-container
    environment:
      PMA_HOST: sae-s4-mysql-container
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "14203:80"
    networks:
      - webdir

  webjs:
    image: nginx-alpine
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - "14204:80"
    networks:
      - webdir

  json-server:
    image: nginx:latest
    volumes:
      - ./web/data.json:/usr/share/nginx/html/data.json
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "14205:80"
    networks:
      - webdir



