name: webdir_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  faker: ^2.0.0
  url_launcher: ^6.1.6
  provider: ^5.0.0
  http: ^1.2.1


  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

 
  uses-material-design: true

 