networks:
  webdir:
    driver: bridge

services:
  php:
    image: canals/php:latest
    container_name: php-container
    ports:
      - "14200:80"
    depends_on:
      - mysql
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
    networks:
      - webdir

  mysql:
    image: mariadb:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "14201:3306"
    networks:
      - webdir

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql-container
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "14202:80"
    networks:
      - webdir