networks:
  jstempapi:
    driver: bridge

services:

  webjs:
    image: node
    volumes:
      - ./:/var/www/html
    ports:
      - "14210:3000"
    depends_on:
      - json-server
    networks:
      - jstempapi

  json-server:
    image: nginx:latest
    volumes:
      - ./data.json:/usr/share/nginx/html/data.json
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "14211:80"
    networks:
      - jstempapi
